#
# Faraday common essential drivers & utilities
#
obj-  :=
obj-n :=
obj-y :=

obj-$(CONFIG_FTSCU100)		+= ftscu100.o

obj-$(CONFIG_SMP)           += platsmp.o headsmp.o
obj-$(CONFIG_HOTPLUG_CPU)   += hotplug.o

obj-$(CONFIG_FTPCIE_CDNG2)  += ftpcie_cdng2.o
