# Core
obj-$(CONFIG_PINCTRL_FTSCU010)	+= pinctrl-ftscu010.o

# SoC Drivers
obj-$(CONFIG_PINCTRL_A380)	+= pinctrl-a380.o
obj-$(CONFIG_PINCTRL_A500)	+= pinctrl-a500.o
obj-$(CONFIG_PINCTRL_LEO)	+= pinctrl-leo.o
obj-$(CONFIG_PINCTRL_TX5)	+= pinctrl-tx5.o
