
# Makefile for Faraday board clocks

obj-y	+= clk.o clk-pll.o

obj-$(CONFIG_MACH_A380)	+= clk-a380.o
obj-$(CONFIG_A500_PLATFORM)	+= clk-a500.o
obj-$(CONFIG_A600_PLATFORM)	+= clk-a600.o
obj-$(CONFIG_MACH_TS711) += clk-ts711.o
obj-$(CONFIG_MACH_LEO)	+= clk-leo.o
obj-$(CONFIG_TX5_PLATFORM)	+= clk-tx5.o
