# SPDX-License-Identifier: GPL-2.0
dtb-$(CONFIG_A500_PLATFORM) += faraday-a500.dtb
dtb-$(CONFIG_A600_PLATFORM) += faraday-a600.dtb faraday-a600_trustzone.dtb faraday-a600_haps.dtb
dtb-$(CONFIG_TX5_PLATFORM)  += faraday-tx5.dtb
